# **MERGE( )- It is column based**

In [7]:
import pandas as pd
df1= pd.DataFrame({'A':[2,3,4,5],'B':["A","B","C","D"]})
df2= pd.DataFrame({'A':[2,4,6,8],'B':["A","C","E","F"]})
# By default, pd.merge performs an 'inner' join and merges on all common column names.
# In this case, 'A' and 'B' are common columns.
# It will find rows where both 'A' and 'B' values match in both DataFrames.
pd.merge(df1,df2)

   A  B
0  2  A
1  4  C

In [8]:
import pandas as pd
df1= pd.DataFrame({'A':[2,3,4,5],'B':["A","B","C","D"]})
df2= pd.DataFrame({'A':[2,4,6,8],'B':["A","C","E","F"]})
# By default, pd.merge performs an 'inner' join and merges on all common column names.
# In this case, 'A' and 'B' are common columns.
# It will find rows where both 'A' and 'B' values match in both DataFrames.
df3=pd.merge(df1,df2)
print(df3)

   A  B
0  2  A
1  4  C

In [ ]:
import pandas as pd
df1= pd.DataFrame({'A':[2,3,4,5],'B':["A","B","C"]})      #all must be of same length
df2= pd.DataFrame({'A':[2,4,6,8],'B':["A","C","E","F"]})
df3=pd.merge(df1,df2)
print(df3)

   A  B
0  2  A
1  4  C

In [ ]:
import pandas as pd
df1= pd.DataFrame({'A':[2,3,4,5],'B':["A","B","C","D"]})
df2= pd.DataFrame({'A':[2,4,6,8],'C':["A","C","E","F"]})
df3=pd.merge(df1,df2) #by default inner
print(df3)

   A  B  C
0  2  A  A
1  4  C  C

In [ ]:
import pandas as pd
df1= pd.DataFrame({'A':[2,3,4,5],'B':["A","B","C","D"]})
df2= pd.DataFrame({'A':[2,4,6,8],'C':["A","C","E","F"]})
df3=pd.merge(df1,df2,on='A',how='left')    #on left position

   A  B    C
0  2  A    A
1  3  B  NaN
2  4  C    C
3  5  D  NaN

In [ ]:
import pandas as pd
df1= pd.DataFrame({'A':[2,3,4,5],'B':["A","B","C","D"]})
df2= pd.DataFrame({'A':[2,4,6,8],'C':["A","C","E","F"]})
df3=pd.merge(df1,df2,on='A',how='right')   #on right
print(df3)

   A    B  C
0  2    A  A
1  4    C  C
2  6  NaN  E
3  8  NaN  F

In [ ]:
import pandas as pd
df1= pd.DataFrame({'A':[2,3,4,5],'B':["A","B","C","D"]})
df2= pd.DataFrame({'A':[2,4,6,8],'C':["A","C","E","F"]})
df3=pd.merge(df1,df2,on='A',how='outer')    #outer is same as right
print(df3)

   A    B    C
0  2    A    A
1  3    B  NaN
2  4    C    C
3  5    D  NaN
4  6  NaN    E
5  8  NaN    F

In [ ]:
import pandas as pd
df1= pd.DataFrame({'A':[1,2,3,4],'B':[10,20,30,40]})                          #output will not come as it will confuse because there is not "on" or "how"
df2= pd.DataFrame({'A':[1,2,3,4],'B':[100,200,300,400]})
pd.merge(df1,df2)

Empty DataFrame
Columns: [A, B]
Index: []

In [3]:
import pandas as pd
df1= pd.DataFrame({'A':[1,2,3,4],'A':[10,20,30,40]})
df2= pd.DataFrame({'B':[1,2,3,4],'B':[100,200,300,400]})
pd.merge(df1,df2)

   A  B_values  C_values
0  3        30       100
1  4        40       200

In [10]:
import pandas as pd
df1= pd.DataFrame({'A':[1,2,3,4],'A':[10,20,30,40]})                          #output will not come as it will confuse because there is not "on" or "how"
df2= pd.DataFrame({'A':[1,2,3,4],'A':[100,200,300,400]})
pd.merge(df1,df2)

Empty DataFrame
Columns: [A]
Index: []

In [ ]:
import pandas as pd
V1= pd.DataFrame({'Rollno':[2,3,4,5],'Name':["A","B","C","D"]})
V2= pd.DataFrame({'Rollno':[2,3,4,5],'Marks':[50,40,30,20]})
SI=pd.merge(V1,V2)
print(SI)

   Rollno Name  Marks
0       2    A     50
1       3    B     40
2       4    C     30
3       5    D     20

In [ ]:
import pandas as pd
V1= pd.DataFrame({'Rollno':[2,3,4,5,6],'Name':["Sadaf","Umang","Kani","Riya","Siya"]})
V2= pd.DataFrame({'Rollno':[2,3,4,5,6],'Marks':[50,40,30,20,10]})
SI=pd.merge(V1,V2)               #Simple merging
print(SI)

   Rollno   Name  Marks
0       2  Sadaf     50
1       3  Umang     40
2       4   Kani     30
3       5   Riya     20
4       6   Siya     10

In [ ]:
import pandas as pd
V1= pd.DataFrame({'Rollno':[2,3,4,5],'Name':["A","B","C","D"]})
V2= pd.DataFrame({'Rollno':[2,3,4,5],'Marks':[50,40,30,20]})
SI=pd.merge(V1,V2,how="inner")
print(SI)

   Rollno Name  Marks
0       2    A     50
1       3    B     40
2       4    C     30
3       5    D     20

In [ ]:
import pandas as pd
V1= pd.DataFrame({'Rollno':[2,3,4,5],'Name':["A","B","C","D"]})
V2= pd.DataFrame({'Rollno':[2,3,4,5],'Marks':[50,40,30,20]})
SI=pd.merge(V1,V2,how="outer")
print(SI)

   Rollno Name  Marks
0       2    A     50
1       3    B     40
2       4    C     30
3       5    D     20

In [ ]:
import pandas as pd
V1= pd.DataFrame({'Rollno':[2,3,4,5],'Name':["A","B","C","D"]})
V2= pd.DataFrame({'Rollno':[2,3,4,5],'Marks':[50,40,30,20]})
SI=pd.merge(V1,V2,how="inner")
print(SI)

   Rollno Name  Marks
0       2    A     50
1       3    B     40
2       4    C     30
3       5    D     20

In [ ]:
import pandas as pd
V1= pd.DataFrame({'Rollno':[2,3,4,5],'Name':["A","B","C","D"]})
V2= pd.DataFrame({'Rollno':[2,3,4,5],'Marks':[50,40,30,20]})
SI=pd.merge(V1,V2,how="left")
print(SI)

   Rollno Name  Marks
0       2    A     50
1       3    B     40
2       4    C     30
3       5    D     20

In [ ]:
import pandas as pd
V1= pd.DataFrame({'Rollno':[2,3,4,5],'Name':["A","B","C","D"]})
V2= pd.DataFrame({'Rollno':[2,3,4,5],'Marks':[50,40,30,20]})
SI=pd.merge(V1,V2,how="right")
print(SI)

   Rollno Name  Marks
0       2    A     50
1       3    B     40
2       4    C     30
3       5    D     20

In [ ]:
import pandas as pd
V1= pd.DataFrame({'Rollno':[2,3,4,6],'Name':["A","B","C","D"]})
V2= pd.DataFrame({'Rollno':[2,3,4,5],'Marks':[50,40,30,20]})
SI=pd.merge(V1,V2,how="inner")
print(SI)

   Rollno Name  Marks
0       2    A     50
1       3    B     40
2       4    C     30

In [ ]:
import pandas as pd
V1= pd.DataFrame({'Rollno':[2,3,4,7],'Name':["A","B","C","D"]})
V2= pd.DataFrame({'Rollno':[2,3,4,5],'Marks':[50,40,30,20]})
SI=pd.merge(V1,V2,how="outer")
print(SI)

   Rollno Name  Marks
0       2    A   50.0
1       3    B   40.0
2       4    C   30.0
3       5  NaN   20.0
4       7    D    NaN

In [ ]:
import pandas as pd
V1= pd.DataFrame({'Rollno':[2,3,4,9],'Name':["A","B","C","D"]})
V2= pd.DataFrame({'Rollno':[2,3,4,5],'Marks':[50,40,30,20]})
SI=pd.merge(V1,V2,how="left")
print(SI)

   Rollno Name  Marks
0       2    A   50.0
1       3    B   40.0
2       4    C   30.0
3       9    D    NaN

In [ ]:
import pandas as pd
V1= pd.DataFrame({'Rollno':[2,3,4,8],'Name':["A","B","C","D"]})
V2= pd.DataFrame({'Rollno':[2,3,4,5],'Marks':[50,40,30,20]})
SI=pd.merge(V1,V2,how="right")
print(SI)

   Rollno Name  Marks
0       2    A     50
1       3    B     40
2       4    C     30
3       5  NaN     20

In [ ]:
import pandas as pd
V1= pd.DataFrame({'Rollno':[2,3,4,7],'Name':["A","B","C","D"]})
V2= pd.DataFrame({'Rollno':[2,3,4,5],'Marks':[50,40,30,20]})
SI=pd.merge(V1,V2,how="outer",indicator=True)
print(SI)

   Rollno Name  Marks      _merge
0       2    A   50.0        both
1       3    B   40.0        both
2       4    C   30.0        both
3       5  NaN   20.0  right_only
4       7    D    NaN   left_only

In [ ]:
import pandas as pd
V1= pd.DataFrame({'Rollno':[2,3,4,7],'Name':["Sadaf","Umi","Kani","Riya"]})
V2= pd.DataFrame({'Rollno':[2,3,4,5],'Name':["Hyy","F","C","D"]})
SI=pd.merge(V1,V2,how="outer")
print(SI)

   Rollno   Name
0       2    Hyy
1       2  Sadaf
2       3      F
3       3    Umi
4       4      C
5       4   Kani
6       5      D
7       7   Riya

In [ ]:
import pandas as pd
V1= pd.DataFrame({'Rollno':[2,3,4,7],'Name':["Sadaf","Umi","Kani","Riya"]})
V2= pd.DataFrame({'Rollno':[2,3,4,5],'Name':["Tiya","Mansi","Khushi","Sachi"]})
SI=pd.merge(V1,V2,right_index=True,left_index=True)
print(SI)

   Rollno_x Name_x  Rollno_y  Name_y
0         2  Sadaf         2    Tiya
1         3    Umi         3   Mansi
2         4   Kani         4  Khushi
3         7   Riya         5   Sachi

In [ ]:
import pandas as pd
V1= pd.DataFrame({'Rollno':[1,2,3,4],'Name':["Sadaf","Umi","Kani","Riya"]})
V2= pd.DataFrame({'Rollno':[1,2,3,4],'Name':["Tiya","Mansi","Khushi","Sachi"]})
SI=pd.merge(V1,V2,right_index=True,left_index=True,suffixes=('_9th','_10th'))     #using suffixes here
print(SI)

   Rollno_9th Name_9th  Rollno_10th Name_10th
0           1    Sadaf            1      Tiya
1           2      Umi            2     Mansi
2           3     Kani            3    Khushi
3           4     Riya            4     Sachi

# **JOIN( )- It is index based**

In [ ]:
import pandas as pd
V1= pd.DataFrame({'Rollno':[2,3,4,5],'Name':["Sadaf","Umi","Kani","Riya"]})      #Column names should be different otherwise error will come
V2= pd.DataFrame({'ID':[2,3,4,5],'Name2':["Tiya","Mansi","Khushi","Sachi"]})
V1.join(V2)

   Rollno   Name  ID   Name2
0       2  Sadaf   2    Tiya
1       3    Umi   3   Mansi
2       4   Kani   4  Khushi
3       5   Riya   5   Sachi

In [ ]:
import pandas as pd
V1= pd.DataFrame({'Rollno':[2,3,4,5],'Name':["Sadaf","Umi","Kani","Riya"]},index=['a','b','c','d'])
V2= pd.DataFrame({'ID':[2,3,4,5],'Name2':["Tiya","Mansi","Khushi","Sachi"]})
V1.join(V2)

   Rollno   Name  ID Name2
a       2  Sadaf NaN   NaN
b       3    Umi NaN   NaN
c       4   Kani NaN   NaN
d       5   Riya NaN   NaN

In [ ]:
import pandas as pd
V1= pd.DataFrame({'Rollno':[2,3,4,5],'Name':["Sadaf","Umi","Kani","Riya"]},index=[1,2,3,4])
V2= pd.DataFrame({'ID':[2,3,4,5],'Name2':["Tiya","Mansi","Khushi","Sachi"]})
V1.join(V2)

   Rollno   Name   ID   Name2
1       2  Sadaf  3.0   Mansi
2       3    Umi  4.0  Khushi
3       4   Kani  5.0   Sachi
4       5   Riya  NaN     NaN

In [ ]:
import pandas as pd
V1= pd.DataFrame({'Rollno':[2,3,4,5],'Name':["Sadaf","Umi","Kani","Riya"]},index=["A","B","C","D"])
V2= pd.DataFrame({'ID':[20,30],'Name2':["Tiya","Mansi"]},index=["A","B"])
V1.join(V2)

   Rollno   Name    ID  Name2
A       2  Sadaf  20.0   Tiya
B       3    Umi  30.0  Mansi
C       4   Kani   NaN    NaN
D       5   Riya   NaN    NaN

In [ ]:
import pandas as pd
V1= pd.DataFrame({'Rollno':[2,3,4,5],'Name':["Sadaf","Umi","Kani","Riya"]},index=["A","B","C","D"])
V2= pd.DataFrame({'ID':[20,30],'Name2':["Tiya","Mansi"]},index=["E","F"])
V2.join(V1)

   ID  Name2  Rollno Name
E  20   Tiya     NaN  NaN
F  30  Mansi     NaN  NaN

In [ ]:
import pandas as pd
V1= pd.DataFrame({'Rollno':[2,3,4,5],'Name':["Sadaf","Umi","Kani","Riya"]},index=["A","B","C","D"])
V2= pd.DataFrame({'ID':[20,30],'Name2':["Tiya","Mansi"]},index=["C","D"])
V2.join(V1,how="inner")

   ID  Name2  Rollno  Name
C  20   Tiya       4  Kani
D  30  Mansi       5  Riya

In [ ]:
import pandas as pd
V1= pd.DataFrame({'Rollno':[2,3,4,5],'Name':["Sadaf","Umi","Kani","Riya"]},index=["A","B","C","D"])
V2= pd.DataFrame({'ID':[20,30],'Name2':["Tiya","Mansi"]},index=["C","D"])
V2.join(V1,how="outer")

     ID  Name2  Rollno   Name
A   NaN    NaN       2  Sadaf
B   NaN    NaN       3    Umi
C  20.0   Tiya       4   Kani
D  30.0  Mansi       5   Riya

In [ ]:
import pandas as pd
V1= pd.DataFrame({'Rollno':[2,3,4,5],'Name':["Sadaf","Umi","Kani","Riya"]},index=["A","B","C","D"])
V2= pd.DataFrame({'ID':[20,30],'Name2':["Tiya","Mansi"]},index=["C","D"])
V2.join(V1,how="left")

   ID  Name2  Rollno  Name
C  20   Tiya       4  Kani
D  30  Mansi       5  Riya

In [ ]:
import pandas as pd
V1= pd.DataFrame({'Rollno':[2,3,4,5],'Name':["Sadaf","Umi","Kani","Riya"]},index=["A","B","C","D"])
V2= pd.DataFrame({'ID':[20,30],'Name2':["Tiya","Mansi"]},index=["C","D"])
V2.join(V1,how="right")

     ID  Name2  Rollno   Name
A   NaN    NaN       2  Sadaf
B   NaN    NaN       3    Umi
C  20.0   Tiya       4   Kani
D  30.0  Mansi       5   Riya

In [5]:
import pandas as pd
V1= pd.DataFrame({'Rollno':[2,3,4,5],'Name':["Sadaf","Umi","Kani","Riya"]},index=["A","B","C","D"])
V2= pd.DataFrame({'Rollno':[20,30],'Name2':["Tiya","Mansi"]},index=["C","D"])    #error will come because col. name is same
# To fix the 'columns overlap but no suffix specified' error, provide suffixes for the overlapping columns.
# 'lsuffix' is for the left DataFrame (V2) and 'rsuffix' is for the right DataFrame (V1).
SI = V2.join(V1,how="right", lsuffix='_v2', rsuffix='_v1')
print(SI)

   Rollno_v2  Name2  Rollno_v1   Name
A        NaN    NaN          2  Sadaf
B        NaN    NaN          3    Umi
C       20.0   Tiya          4   Kani
D       30.0  Mansi          5   Riya

In [ ]:
import pandas as pd
V1= pd.DataFrame({'Rollno':[2,3,4,5],'Name':["Sadaf","Umi","Kani","Riya"]},index=["A","B","C","D"])
V2= pd.DataFrame({'ID':[20,30],'Name2':["Tiya","Mansi"]},index=["C","D"])
V1.join(V2,lsuffix='_left')      #to customize it using suffix

   Rollno   Name    ID  Name2
A       2  Sadaf   NaN    NaN
B       3    Umi   NaN    NaN
C       4   Kani  20.0   Tiya
D       5   Riya  30.0  Mansi

In [ ]:
import pandas as pd
V1= pd.DataFrame({'Rollno':[2,3,4,5],'Name':["Sadaf","Umi","Kani","Riya"]},index=["A","B","C","D"])
V2= pd.DataFrame({'ID':[20,30],'Name2':["Tiya","Mansi"]},index=["C","D"])
V3= pd.DataFrame({'Num':[40,50],'Name3':["Jiya","Shivani"]},index=["C","D"])
V1.join([V2,V3])       #More than 2,then list will be there

   Rollno   Name    ID  Name2   Num    Name3
A       2  Sadaf   NaN    NaN   NaN      NaN
B       3    Umi   NaN    NaN   NaN      NaN
C       4   Kani  20.0   Tiya  40.0     Jiya
D       5   Riya  30.0  Mansi  50.0  Shivani

In [ ]:
import pandas as pd
V1= pd.DataFrame({'Rollno':[2,3,4,5],'Name':["Sadaf","Umi","Kani","Riya"]},index=["A","B","C","D"])
V2= pd.DataFrame({'ID':[20,30],'Name2':["Tiya","Mansi"]},index=["C","D"])
V3= pd.DataFrame({'Num':[40,50],'Name3':["Jiya","Shivani"]},index=["C","D"])
V1.join(V2).join(V3)

   Rollno   Name    ID  Name2   Num    Name3
A       2  Sadaf   NaN    NaN   NaN      NaN
B       3    Umi   NaN    NaN   NaN      NaN
C       4   Kani  20.0   Tiya  40.0     Jiya
D       5   Riya  30.0  Mansi  50.0  Shivani

# **CONCAT( )- adds data rather focusing on col. name or index**

In [ ]:
import pandas as pd
roll_no=pd.Series([1,2,3,4])
roll_no2=pd.Series([10,20,30,40])
pd.concat([roll_no,roll_no2],axis=0)   #like a line

0     1
1     2
2     3
3     4
0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
import pandas as pd
roll_no=pd.Series([1,2,3,4])
roll_no2=pd.Series([10,20,30,40])
pd.concat([roll_no,roll_no2],axis=1)    #by using axis=1, adding col. at side of it

   0   1
0  1  10
1  2  20
2  3  30
3  4  40

In [ ]:
import pandas as pd
roll_no=pd.Series([1,2,3,4])
roll_no2=pd.Series([10,20,30,40])
pd.concat([roll_no,roll_no2],axis=0,ignore_index=True)   #by using ignore index, it is not repeating the index value again like previous one

0     1
1     2
2     3
3     4
4    10
5    20
6    30
7    40
dtype: int64

In [ ]:
df1= pd.DataFrame({'A':[1,2,3],'B':["A","B","C"]})
df2= pd.DataFrame({'A':[2,4,6],'B':["A","C","E"]})   #not overriding, as used same col. names
pd.concat([df1,df2],axis=1)

   A  B  A  B
0  1  A  2  A
1  2  B  4  C
2  3  C  6  E

In [ ]:
df1= pd.DataFrame({'A':[1,2,3],'B':["A","B","C"]})
df2= pd.DataFrame({'D':[2,4,6],'E':["A","C","E"]})
pd.concat([df1,df2],axis=1)

   A  B  D  E
0  1  A  2  A
1  2  B  4  C
2  3  C  6  E

In [ ]:
df1= pd.DataFrame({'A':[1,2,3],'B':["A","B","C"]})
df2= pd.DataFrame({'D':[2,4,6],'E':["A","C","E"]})
pd.concat([df1,df2],join="inner")  #only iinner/outer can be done

Empty DataFrame
Columns: []
Index: [0, 1, 2, 0, 1, 2]

In [ ]:
df1= pd.DataFrame({'A':[1,2,3],'B':["A","B","C"]})
df2= pd.DataFrame({'D':[2,4,6],'E':["A","C","E"]})
pd.concat([df1,df2],join="right")    #right/left cannot be done, error will come

ValueError: Only can inner (intersect) or outer (union) join the other axis

In [12]:
df1= pd.DataFrame({'A':[1,2,3],'B':["A","B","C"]})
df2= pd.DataFrame({'D':[2,4,6],'E':["A","C","E"]})
# When concatenating with 'outer' join (default for columns when axis=0 or rows when axis=1),
#fills NaN for values not present in both.
pd.concat([df1,df2],join="outer")

     A    B    D    E
0  1.0    A  NaN  NaN
1  2.0    B  NaN  NaN
2  3.0    C  NaN  NaN
0  NaN  NaN  2.0    A
1  NaN  NaN  4.0    C
2  NaN  NaN  6.0    E

In [11]:
df1= pd.DataFrame({'A':[1,2,3],'B':["A","B","C"]})
df2= pd.DataFrame({'D':[2,4,6],'E':["A","C","E"]})
# Concatenate df1 and df2 along axis=1 (horizontally).

# assigning 'A' to columns from df1 and 'B' to columns from df2.
pd.concat([df1,df2],axis=1,keys=["A","B"])

   A     B
   A  B  D  E
0  1  A  2  A
1  2  B  4  C
2  3  C  6  E

In [ ]:
df1= pd.DataFrame({'A':[1,2,3],'B':["A","B","C"]})
df2= pd.DataFrame({'D':[2,4,6],'E':["A","C","E"]})
pd.concat([df1,df2],axis=0,keys=["A","B"])   #keys used to describe the two names to the table

       A    B    D    E
A 0  1.0    A  NaN  NaN
  1  2.0    B  NaN  NaN
  2  3.0    C  NaN  NaN
B 0  NaN  NaN  2.0    A
  1  NaN  NaN  4.0    C
  2  NaN  NaN  6.0    E

In [ ]:
df1= pd.DataFrame({'A':[1,2,3]})
df2= pd.DataFrame({'D':[2,4,6],'E':["A","C","E"]})
pd.concat([df1,df2],axis=1)   #not dependent on anything,it will run

   A  D  E
0  1  2  A
1  2  4  C
2  3  6  E

In [ ]:
df1= pd.DataFrame({'A':[1,2,3]})
df2= pd.DataFrame({'D':[2,4,6],'E':["A","C","E"]})
pd.concat([df1,df2],axis=0)   #not dependent on anything,it will run

     A    D    E
0  1.0  NaN  NaN
1  2.0  NaN  NaN
2  3.0  NaN  NaN
0  NaN  2.0    A
1  NaN  4.0    C
2  NaN  6.0    E

In [ ]:
df1= pd.DataFrame({'A':[2,4,6,8],'B':["A","B","C","D"]})
df2= pd.DataFrame({'D':[2,4,6],'E':["A","C","E"]})
pd.concat([df1,df2],axis=1)    #not dependent, NaN will come bcoz missing values are there

   A  B    D    E
0  2  A  2.0    A
1  4  B  4.0    C
2  6  C  6.0    E
3  8  D  NaN  NaN