**Data Manipulation using Pandas:**

* Pandas is a powerful Python library used for data manipulation and analysis, providing core data structures like DataFrames and Series.
 * It enables efficient data cleaning, filtering, grouping, merging, and handling of missing values in tabular datasets.
 * It supports reading and writing data across various file formats, making it a cornerstone for data science workflows.

###**1**. Series

* A Pandas Series is a one-dimensional labeled array capable of storing data of any type (integers, strings, floats, etc.).
 * It pairs data values with an associated array of labels known as an index, enabling intuitive and fast data access.
 * Serving as a fundamental building block of Pandas, a Series behaves similarly to a single column in a spreadsheet or a SQL table.

In [ ]:
import pandas as pd   #importing pandas
marks = [2,4,6,8,10]
ds= pd.Series(marks)
print(ds)
print(type(ds))   #printing the type

0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
import pandas as pd
marks = [2,4,6,8,10]       #Customized index
ds= pd.Series(marks, index=["sadaf", "umang", "kani", "riya", "siya"])
print(ds)

sadaf     2
umang     4
kani      6
riya      8
siya     10
dtype: int64

In [ ]:
import pandas as pd
marks = [2,4,6,8,10]       #Customized index
ds= pd.Series(marks, index=["sadaf", "umang", "kani", "riya", "siya"])
print(ds)

sadaf     2
umang     4
kani      6
riya      8
siya     10
dtype: int64

In [ ]:
import pandas as pd
marks = [2,4,6,8,10]       #Customized index
ds= pd.Series(marks, index=["sadaf", "umang", "kani", "riya", "siya"],dtype= "float",name="marksheet record")
print(ds)

sadaf     2.0
umang     4.0
kani      6.0
riya      8.0
siya     10.0
Name: marksheet record, dtype: float64

**1.1 Common Operations**

1.   s.sum()-Calculates and returns the total sum of all numeric  elements in the Pandas Series.
2.   s.mean()- Computes and returns the arithmetic mean (average) of the values in the Series.
3.   s.max()- Returns the highest value present in the Series.
4.   s.min()- Returns the lowest value present in the Series.

In [ ]:
print(ds.sum())
print(f"min num in series:", ds.min())
print(f"min num in series:", ds.max())
print(f"min num in series:", ds.mean())

30
min num in series: 2
min num in series: 10
min num in series: 6.0

**1.3  Indexing and Slicing**


Indexing: Indexing allows you to access a single specific element within a sequence using its numerical position, with indices starting at 0.

Slicing:  Slicing enables the extraction of a subset or range of elements from a sequence using the syntax [start:end:step].

In [ ]:
print(f"Access element by Integer number", {ds[0]})   #accessing a value by integer number

Access element by Integer number {np.int64(2)}

/tmp/ipykernel_1118/2462878888.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Access element by Integer number", {ds[0]})

In [ ]:
print(f"Access element by Variable", ds[2])   #accessing the element by variable

Access element by Variable 6

/tmp/ipykernel_1118/3048248043.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Access element by Variable", ds[2])

In [ ]:
print("slicing in series", ds[0:3])

slicing in series sadaf    2
umang    4
kani     6
dtype: int64

## **1.3 Vectorization Function:**

* Vectorization allows operations to be applied to entire arrays or series simultaneously, eliminating the need for slow, explicit Python for loops.
 * It executes underlying calculations at C-speeds using libraries like NumPy or Pandas, resulting in massive performance boosts for large datasets.
 * This approach yields cleaner, more concise code and improves efficiency by performing fast, element-wise operations under the hood.

In [ ]:
print(ds*3)
print(ds+3)
print(ds-3)
print(ds/3)
print(ds**3)
print(ds%3)

sadaf     6
umang    12
kani     18
riya     24
siya     30
dtype: int64
sadaf     5
umang     7
kani      9
riya     11
siya     13
dtype: int64
sadaf   -1
umang    1
kani     3
riya     5
siya     7
dtype: int64
sadaf    0.666667
umang    1.333333
kani     2.000000
riya     2.666667
siya     3.333333
dtype: float64
sadaf       8
umang      64
kani      216
riya      512
siya     1000
dtype: int64
sadaf    2
umang    1
kani     0
riya     2
siya     1
dtype: int64

In [ ]:
info= {"name": "chetan", "marks":[20,30,28,21]}     #dictionary in series
ds1= pd.Series(info)
print(ds1)

name               chetan
marks    [20, 30, 28, 21]
dtype: object

In [ ]:
info= {"name": "chetan", "marks":[20,30,28,21]}
ds1= pd.Series(info)
print(ds1)   #printing only ds1 will give the tabular format output.
ds1

name               chetan
marks    [20, 30, 28, 21]
dtype: object

name               chetan
marks    [20, 30, 28, 21]
dtype: object

In [ ]:
ds1["name"]     #working as indexing

'chetan'

**Minimum Series**

In [ ]:
num= pd.Series(5)     #Maximum 1 column and 1 row
print(num)

0    5
dtype: int64

In [ ]:
num= pd.Series(5, index=[1,2,3,4,5])     #Maximum 1 column and multiple rows
print(num)

1    5
2    5
3    5
4    5
5    5
dtype: int64

In [ ]:
num1= pd.Series(5, index=[1,2,3,4,5])     #same indexing se hojayega
num2= pd.Series(10, index=[1,2,3,4,5])
print(num1+num2)

1    15
2    15
3    15
4    15
5    15
dtype: int64

In [ ]:
num1= pd.Series(5, index=[1,2,3,4,5])
num2= pd.Series(10, index=[0,5,10,15,25])     #different index se nahi hoga
print(num1+num2)                              #NaN stands for Not a Number

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
5     15.0
10     NaN
15     NaN
25     NaN
dtype: float64

In [ ]:
num1= pd.Series(5, index=[1,2,3,4,5])
num2= pd.Series(10, index=["a","b","c","d","e"])   #non-matching indexes.
print(num1+num2)

1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
dtype: float64

**2.0 Main Data Structures**

**2.1 DataFrame:**




A Pandas DataFrame is a two-dimensional, labeled tabular data structure with rows and columns, closely resembling a spreadsheet or SQL table.

It can store heterogeneous data types across different columns and provides powerful functionality for indexing, alignment, and data manipulation.

As the primary data structure in Pandas, it is widely used in data science for cleaning, filtering, and analyzing large datasets.

In [ ]:
import pandas as pd
Students={
    "Names":["Harsh", "Ankit","Kanishka"],
    "Roll_num": [100,101,102],
    "Marks":[80,86,88]
        }
DF = pd.DataFrame(Students)
print(DF)

      Names  Roll_num  Marks
0     Harsh       100     80
1     Ankit       101     86
2  Kanishka       102     88

In [ ]:
import pandas as pd
Students={
    "Names":["Harsh", "Ankit","Kanishka"]   #error will come as the same length is not there.
    "Roll_num": [100,102]
    "Marks":[80,86,88]
}
DF = pd.DataFrame(Students)
print(DF)

ValueError: All arrays must be of the same length

**Creating a Dataframe with list*

In [ ]:
Studentsinfo=[['A','B','C'], [20,40,60]]
DF= pd.DataFrame(Studentsinfo)
print(DF)     #using here print(DF)

    0   1   2
0   A   B   C
1  20  40  60

In [ ]:
Studentsinfo=[['A','B','C'], [20,40,60]]
DF= pd.DataFrame(Studentsinfo)
DF      #Only using DF

    0   1   2
0   A   B   C
1  20  40  60

***Multiple Series to make Dataframe***

In [ ]:
Sr={
    "Name": pd.Series(['A','B','C','D','E']),
    "Marks": pd.Series([10,20,30,40,50])
}
DF= pd.DataFrame(Sr)
print(DF)

  Name  Marks
0    A     10
1    B     20
2    C     30
3    D     40
4    E     50

**2.2 Performing Arithmetic Operations in DF**

In [ ]:
var= pd.DataFrame({'A':[1,2,3,4,5], 'B':[6,7,8,9,10]})
var["C"]= var["A"]+var['B']
var["C"]= var["A"]-var['B']
var["C"]= var["A"]*var['B']
var["C"]= var["A"]/var['B']
var["C"]= var["A"]%var['B']

var

   A   B  C
0  1   6  1
1  2   7  2
2  3   8  3
3  4   9  4
4  5  10  5

**2.3 Filtering in DF:**

* Data filtering allows you to extract specific subsets of rows from a dataset based on defined conditions or logical expressions.
 * In Pandas, it is commonly performed using boolean indexing, conditional operators, or specialized methods like .loc[].
 * This process is essential for isolating relevant information, removing unwanted noise, and conducting targeted data analysis.

In [ ]:
var= pd.DataFrame({'A':[1,2,3,4,5], 'B':[6,7,8,9,10]})
var["C"]= var["A"]+var['B']
var["pyhton"]=var["C"]>10    #Filtering
var

   A   B   C  pyhton
0  1   6   7   False
1  2   7   9   False
2  3   8  11    True
3  4   9  13    True
4  5  10  15    True

**2.4 Handling Missing Values**

* Handling missing values involves identifying null or NaN entries in a dataset and cleaning them using techniques like imputation or dropping.

In [ ]:
import numpy as np
import pandas as pd
Sr={
    "Name": pd.Series(['Sadaf','Riya',np.nan,'Siya','Kani']),
    "Roll_num": pd.Series([10,20,30,40,50]),
    "Marks": pd.Series([10,20,np.nan,40,50]),
    "Subject":pd.Series(["Hindi","Sans","Maths",np.nan,np.nan]),
    "City":pd.Series(["Meerut","Noida","Delhi",np.nan,"Gurgaon"])
}
DF= pd.DataFrame(Sr)
print(DF)

    Name  Roll_num  Marks Subject     City
0  Sadaf        10   10.0   Hindi   Meerut
1   Riya        20   20.0    Sans    Noida
2    NaN        30    NaN   Maths    Delhi
3   Siya        40   40.0     NaN      NaN
4   Kani        50   50.0     NaN  Gurgaon

* The df.info() method prints a concise summary of a Pandas DataFrame, including its column names, non-null counts, data types, and total memory usage.

In [ ]:
DF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      4 non-null      object
 1   Roll_num  5 non-null      int64
 2   Marks     5 non-null      int64
 3   Subject   3 non-null      object
 4   City      4 non-null      object
dtypes: int64(2), object(3)
memory usage: 332.0+ bytes

* The df.isnull() method returns a boolean-valued DataFrame of the same shape, where True indicates a missing value (NaN) and False represents a valid entry.

In [ ]:
DF.isnull()

    Name  Roll_num  Marks  Subject   City
0  False     False  False    False  False
1  False     False  False    False  False
2   True     False  False    False  False
3  False     False  False     True   True
4  False     False  False     True  False

* The df.isnull().sum() method counts and returns the total number of missing or NaN values for each column in a Pandas DataFrame.

In [ ]:
DF.isnull().sum()

Name        1
Roll_num    0
Marks       0
Subject     2
City        1
dtype: int64

* The print(df.isnull().sum().sum()) command computes and returns the grand total of all missing or NaN values present across the entire Pandas DataFrame.

In [ ]:
print(DF.isnull().sum().sum())

4

* The dropna() method is used to remove rows or columns that contain missing or NaN values from a Pandas DataFrame or Series.

In [ ]:
#remove null values
DF.dropna()

    Name  Roll_num  Marks Subject    City
0  Sadaf        10     10   Hindi  Meerut
1   Riya        20     20    Sans   Noida

In [ ]:
DF.dropna(subset=["Marks"])

    Name  Roll_num  Marks Subject     City
0  Sadaf        10     10   Hindi   Meerut
1   Riya        20     20    Sans    Noida
2    NaN        30     30   Maths    Delhi
3   Siya        40     40     NaN      NaN
4   Kani        50     50     NaN  Gurgaon

In [ ]:
DF["Marks"]=DF["Marks"].fillna(0)
DF

    Name  Roll_num  Marks Subject     City
0  Sadaf        10   10.0   Hindi   Meerut
1   Riya        20   20.0    Sans    Noida
2    NaN        30    0.0   Maths    Delhi
3   Siya        40   40.0     NaN      NaN
4   Kani        50   50.0     NaN  Gurgaon

* The fillna() method is used to replace missing or NaN values in a Pandas DataFrame or Series with specified values, constants, or methods like forward/backward filling.

In [ ]:
DF["Marks"] = DF["Marks"].fillna(DF["Marks"].max())
DF

    Name  Roll_num  Marks Subject     City
0  Sadaf        10   10.0   Hindi   Meerut
1   Riya        20   20.0    Sans    Noida
2    NaN        30    0.0   Maths    Delhi
3   Siya        40   40.0     NaN      NaN
4   Kani        50   50.0     NaN  Gurgaon

In [ ]:
DF["Name"].fillna("Khushi")

0     Sadaf
1      Riya
2    Khushi
3      Siya
4      Kani
Name: Name, dtype: object